# Generated by Django 4.0.1 on 2022-01-05 20:20

from django.db import migrations, models
import soundboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sound',
            name='sound',
            field=models.FileField(max_length=255, upload_to=soundboard.models.sound_directory_path),
        ),
    ]
