# Generated by Django 4.0.1 on 2022-01-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0002_alter_sound_image_alter_sound_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundboard',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
