# Generated by Django 5.0.1 on 2024-02-07 07:19

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0004_alter_sound_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, overwrite=True, populate_from='name'),
        ),
    ]
