# Generated by Django 5.0.1 on 2024-02-07 09:11

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0005_sound_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, null=True, overwrite=True, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='soundboard',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, null=True, overwrite=True, populate_from='name'),
        ),
        migrations.AlterUniqueTogether(
            name='sound',
            unique_together={('slug', 'soundboard')},
        ),
    ]
