# Generated by Django 5.0.2 on 2024-02-21 13:34

import soundboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0006_alter_sound_slug_alter_soundboard_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=soundboard.models.sound_directory_path),
        ),
    ]
